remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Super Simple Automation]
description: [Automation made simple in JavaScript  Python C# and Java \n https://supersimpleautomation.atlassian.net/wiki/spaces/~712020eb83cc7598394306a69db05e779a3dd3/pages]
